heat_template_version: 2013-05-23

description: Ubuntu 64 server Lab on Openstack using static NW.

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  networks:
    type: string
    label: Instance Type
    description: Instance network

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      networks:
      - network: { get_param: networks }
      user_data: |
           #!/bin/bash -v
           apt-get update
           apt-get install ant
